version: "3.0"

services:

  # micro-service gateway
  gateway:
    build:
      context: ./gateway
    ports:
      - 4000:4000
    restart: unless-stopped
    depends_on:
      ms-helo:
        condition: service_healthy
      ms-foo:
        condition: service_healthy

  # micro-service hello
  ms-helo:
    build:
      context: ./ms-helo
      target: development
    ports:
      - 4001:4001
    restart: unless-stopped
    healthcheck:
      test: 'curl localhost:4001/live'
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - .:/workspace:cached

  # micro-service foo
  ms-foo:
    build:
      context: ./ms-foo
      target: development
    ports:
      - 4002:4002
    restart: unless-stopped
    healthcheck:
      test: 'curl localhost:4002/live'
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - .:/workspace:cached

