apiVersion: v1

# namespace
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: gql-federation-demo
  name: gql-federation-demo
---

# deploy microservice ms-foo

# create service ms-foo
apiVersion: v1
kind: Service
metadata:
  name: ms-foo
spec:
  selector:
    app.kubernetes.io/name: ms-foo
  ports:
  - name: ms-foo
    port: 4002
    targetPort: 4002
  type: ClusterIP

# create deployment ms-foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ms-foo
      app: ms-foo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ms-foo
        app: ms-foo
    spec:
      containers:
      - name: ms-foo
        image: docker-dev-env-test-01-ms-foo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4002
        resources:
          requests:
            cpu: 75m
            memory: 64Mi

# deploy microservice ms-helo

# create service ms-helo
---
apiVersion: v1
kind: Service
metadata:
  name: ms-helo
spec:
  selector:
    app.kubernetes.io/name: ms-helo
  ports:
  - name: ms-helo
    port: 4001
    targetPort: 4001
  type: ClusterIP

# create deployment ms-helo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-helo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ms-helo
      app: ms-helo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ms-helo
        app: ms-helo
    spec:
      containers:
      - name: ms-helo
        image: docker-dev-env-test-01-ms-helo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4001
        resources:
          requests:
            cpu: 75m
            memory: 64Mi

# deploy federated gateway

# create service gql-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
  - name: gateway
    port: 4000
    targetPort: 4000
  type: ClusterIP

# create deployment gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app: gateway
    spec:
      containers:
      - name: gateway
        image: docker-dev-env-test-01-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 75m
            memory: 64Mi
